[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_PATHS = "netlify/functions/**,.env*,node_modules/**,*.log"
  SECRETS_SCAN_OMIT_KEYS = "GEMINI_API_KEY"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."generate-website"]
  timeout = 300
  memory = 3008

[functions."health"]
  timeout = 10

[functions."test"]  
  timeout = 10

[functions."simple-test"]  
  timeout = 120

[functions."test-generate"]  
  timeout = 60

[functions."debug-deployment"]  
  timeout = 10

[functions."debug"]  
  timeout = 10

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
